BUILD: quic: fix warning during compilation using gcc-6.5
Building with gcc-6.5:

src/quic_conn.c: In function 'send_retry':
src/quic_conn.c:6554:2: error: dereferencing type-punned pointer will break
strict-aliasing rules [-Werror=strict-aliasing]
   *((uint32_t *)((unsigned char *)&buf[i])) = htonl(qv->num);

This patch use write_n32 to set the value.

This could be backported until v2.6

(cherry picked from commit c0456f45c8aa3173a503dc8d4cd0d4e4f1b29a3b)
Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>