FIXUP: quic_pktns_discard: looks like max_dgram_sz should be uint instead of size_t
include/haproxy/xprt_quic.h:1039:15: error: comparison of distinct pointer types lacks a cast [-Werror]
include/haproxy/xprt_quic.h:1039:15: error: comparison of distinct pointer types lacks a cast [-Werror]